# @format

name: Continuous Integration

on:
    push:
        branches: [main]

jobs:
    test_push:
        runs_on: ubuntu-latest
        steps:
            - uses: actions/chechout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm run test
